# Generated by Django 3.1.3 on 2020-12-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercostume',
            old_name='name',
            new_name='name2',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
