# Generated by Django 3.1.3 on 2020-12-14 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0003_auto_20201214_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Survey.option'),
            preserve_default=False,
        ),
    ]
