# Generated by Django 3.1.3 on 2020-12-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0005_auto_20201214_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='rate',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
