# Generated by Django 3.1.3 on 2020-12-14 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0006_auto_20201214_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AddField(
            model_name='option',
            name='options',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Survey.question'),
            preserve_default=False,
        ),
    ]
