# Generated by Django 3.1.3 on 2020-12-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0007_auto_20201214_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='options',
            new_name='Question',
        ),
    ]
