# Generated by Django 3.1.3 on 2020-12-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0008_auto_20201214_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='Question',
            new_name='question',
        ),
    ]
